version: "3"

tasks:
  up:
    desc: Docker compose up
    cmds:
      - docker compose -f docker-compose.yml up --build

  cucumber:
    desc: Run cucumber tests
    cmds:
      - docker compose -f {{.CUCUMBER_COMPOSE_FILE}} up --build --abort-on-container-exit
    requires:
      vars: [CUCUMBER_COMPOSE_FILE]
